cat: node23: No such file or directory
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/autograd/__init__.py:175: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 64], strides() = [1, 1]
bucket_view.sizes() = [1, 64], strides() = [64, 1] (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484809535/work/torch/csrc/distributed/c10d/reducer.cpp:312.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/autograd/__init__.py:175: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 64], strides() = [1, 1]
bucket_view.sizes() = [1, 64], strides() = [64, 1] (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484809535/work/torch/csrc/distributed/c10d/reducer.cpp:312.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/home/dat-share/zyx/REANN-github-0408-Z/reann_test2502_stress_add/__main__.py", line 1, in <module>
    import run.train
  File "/public/home/dat-share/zyx/REANN-github-0408-Z/reann_test2502_stress_add/run/train.py", line 149, in <module>
    data_train,data_test,force_train_size,force_test_size,Prop_class,loss_fn,optim,scheduler,ema,restart,PES_Normal,device,PES_Lammps=None)
  File "/public/home/dat-share/zyx/REANN-github-0408-Z/reann_test2502_stress_add/src/optimize.py", line 23, in Optimize
    loss=loss_fn(Prop_class(cart,numatoms,species,atom_index,shifts,volume,force_train_sizee),abProp)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 994, in forward
Traceback (most recent call last):
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/home/dat-share/zyx/REANN-github-0408-Z/reann_test2502_stress_add/__main__.py", line 1, in <module>
    import run.train
  File "/public/home/dat-share/zyx/REANN-github-0408-Z/reann_test2502_stress_add/run/train.py", line 149, in <module>
    data_train,data_test,force_train_size,force_test_size,Prop_class,loss_fn,optim,scheduler,ema,restart,PES_Normal,device,PES_Lammps=None)
  File "/public/home/dat-share/zyx/REANN-github-0408-Z/reann_test2502_stress_add/src/optimize.py", line 23, in Optimize
    loss=loss_fn(Prop_class(cart,numatoms,species,atom_index,shifts,volume,force_train_sizee),abProp)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 994, in forward
        if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeErrorRuntimeError: : Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this errorExpected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

terminate called without an active exception
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 81919 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 81918) of binary: /public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/bin/python
Traceback (most recent call last):
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/public/software/anaconda3/envs/pytorch-1.12.1-gpu-11.3/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/public/home/dat-share/zyx/REANN-github-0408-Z/reann_test2502_stress_add/ FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-06_11:36:36
  host      : gpu1
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 81918)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 81918
============================================================
